### ISSUE TITLE
NullReferenceException with empty attribute value

### ISSUE THREAD

**Issue by anvish** [KirillOsenkov/XmlParser#1]
XmlAttributeSyntax:
    public string Value
    {
      get
      {
        ...
        return xmlStringSyntax.TextTokens.Node.ToFullString();
      }
    }

xmlStringSyntax.TextTokens.Node == null

**Comment by KirillOsenkov** [comment]
Do you have an XML fragment for which this reproduces? Or a unit-test?

**Comment by KirillOsenkov** [comment]
Never mind. Fixed with commit https://github.com/KirillOsenkov/XmlParser/commit/9e8266c8b34c6f42d058c99cffddf421ad851fee
