### ISSUE TITLE
Environment.NewLine is not always "\r\n"

### ISSUE THREAD

**Issue by tintoy** [KirillOsenkov/XmlParser#11]
Hi - just a quick one; looks like the code below causes issues on non-Windows platforms:

https://github.com/KirillOsenkov/XmlParser/blob/be216f0851f6445bb50307997654c7e07595fde9/src/Microsoft.Language.Xml/Scanner.cs#L2188

On non-windows platforms, `Environment.NewLine` is `\n` not `\r\n` and so the library yields a slightly different syntax tree for the same text.

**Comment by tintoy** [comment]
BTW, I'm using a custom-built package with this change and it's fixed my issue (each line's effective column offsets were off by 1 less than the line before) - happy to contribute it back, but if not I'm happy on this end too.

**Comment by KirillOsenkov** [comment]
Interesting, so you're saying it should replace Environment.NewLine with hardcoded "\r\n"? I think this makes sense. Would you send a PR for this? Thanks!
