### ISSUE TITLE
Strong signing for using in Vsix

### ISSUE THREAD

**Issue by flcdrg** [KirillOsenkov/XmlParser#2]
I wanted to use this parser in an extension I'm working on (https://github.com/flcdrg/XsltCop), but it needs to have a strong name for me to add as an assembly reference.

I could compile it locally, but would be nicer to just consume the NuGet package directly :-)

**Comment by KirillOsenkov** [comment]
Fixed and published NuGets 1.0.13. Hope this works fine.

**Comment by flcdrg** [comment]
Thanks! Works great :-)
