### ISSUE TITLE
Using in Visual Studio

### ISSUE THREAD

**Issue by shmuelie** [KirillOsenkov/XmlParser#38]
Is there a VSIX or other way to add the language services to VS?

**Comment by KirillOsenkov** [comment]
Unfortunately not. Visual Studio already has an XML language service, and this would be a replacement. There's nothing in this repo that Visual Studio already doesn't support (unless I'm missing something?)

**Comment by shmuelie** [comment]
Yes. Though I was hoping/thinking about if it could be used to create "Roslyn analyzers" but for XML, which would require it to be the language service.

**Comment by KirillOsenkov** [comment]
I see. You want extensibility. You’d need to replace the XML editor in VS with this one, then you could add extensions. 

Maybe one day.

**Comment by shmuelie** [comment]
Guess just dream for now.
