### ISSUE TITLE
Double closing slash creates null trivia

### ISSUE THREAD

**Issue by grokys** [KirillOsenkov/XmlParser#59]
The following XML:

```
"<a><b><//b></a>"
```

Creates a root element with leading trivia containing null (which incidentally seems to break the VS debugger ;) )

<img width="623" alt="image" src="https://github.com/KirillOsenkov/XmlParser/assets/1775141/fa2773eb-7188-48ba-a3f2-560bab22d24e">

<img width="622" alt="image" src="https://github.com/KirillOsenkov/XmlParser/assets/1775141/a40b1567-bb34-4363-bd20-3449a9377d67">

**Comment by grokys** [comment]
Seems to be caused by `SyntaxTriviaList.this[]` failing to cast a `SkippedTokensTriviaSyntax` to `SyntaxTrivia`:

<img width="562" alt="image" src="https://github.com/KirillOsenkov/XmlParser/assets/1775141/534529a9-6e05-4852-bf02-5568a7f8d6c6">

**Comment by KirillOsenkov** [comment]
Indeed ;)

![image](https://github.com/KirillOsenkov/XmlParser/assets/679326/042ca406-b51f-40d8-a980-ee351e9b8cbe)

**Comment by grokys** [comment]
Adding the following check to `SyntaxTriviaList.ctor` shows up a few places where this could potentially fail:

```
            if (!node.IsList && node is not SyntaxTrivia)
                throw new ArgumentException($"Node {node} must be a SyntaxTrivia");
```

**Comment by KirillOsenkov** [comment]
This is how it works in C#:
https://github.com/dotnet/roslyn/blob/7ecf61f6d02b5605c97da1408e0440548f6bf863/src/Compilers/Core/Portable/Syntax/SyntaxTriviaList.cs#L138

**Comment by KirillOsenkov** [comment]
I have no idea about this space but I'm trying to figure it out.

**Comment by grokys** [comment]
Yeah, not really sure how this should work: the C# version is sufficiently different that I'm not sure what applies here and what doesn't.

**Comment by KirillOsenkov** [comment]
what I'm seeing is this cast returns null:
https://github.com/KirillOsenkov/XmlParser/blob/a407b1a4d353fe22e641f5d6b49170c74128c85a/src/Microsoft.Language.Xml/Syntax/SyntaxTriviaList.cs#L738

_current is a valid SkippedTokensTriviaSyntax, which is a syntax node, not syntax trivia

**Comment by KirillOsenkov** [comment]
Completely unrelated, but making sure you know about 
https://xmlsyntaxvisualizer.azurewebsites.net

**Comment by KirillOsenkov** [comment]
Published https://www.nuget.org/packages/GuiLabs.Language.Xml/1.2.91, try it out and see if it works?

I'm not 100% that this is the right fix, but conceptually I think when you iterate to get trivia from the list it needs to be "flattened", since skipped tokens is stored as a structured tree with nodes, but trivia pretty much seems to be glorified plaintext.

I'll try and double-check later with the Roslyn compiler team to see if this makes sense. But at least this is better than crashing for now and I added a test that verifies that if you iterate over all tokens and trivia you get the exact original text back.

**Comment by grokys** [comment]
Thanks @KirillOsenkov - that seems to fix the null reference exception at least!

**Comment by KirillOsenkov** [comment]
FYI @grokys I got an explanation from @cyrusnajmabadi about structured trivia in Roslyn, hope you find this educational:
https://github.com/KirillOsenkov/Bliki/wiki/Roslyn-Structured-Trivia
