### ISSUE TITLE
Is is possible to extend the parser ?

### ISSUE THREAD

**Issue by springcomp** [KirillOsenkov/XmlParser#60]
I would like to be able to parse DSL languages that piggy-back on XML.
One of these lives in [Azure API Management XML policies](https://learn.microsoft.com/en-us/azure/api-management/api-management-policy-expressions).

One example would look like:

```xml
<policies>
  <inbound>
    <set-variable name="addition" value="@( 1 + 1 )" />
    <set-variable name="constant" value="@( "hello, world" )" />
    <set-variable name="indirect" value="@( context.Variables.GetValueOrDefault<string>("constant", "n/a") )" />
    <base />
  </inbound>
</policies>
```
You can see that the policy is no longer a valid XML file as it includes C# statements enclosed within `@( … )` delimiters inside attributes.
My assumption is that, instead of producing an invalid syntax, new syntax nodes would be attached to the AST.

Is it possible to extend this project to host custom syntax nodes at specific places ?

**Comment by KirillOsenkov** [comment]
this project is not extensible, but you should check out https://github.com/mhutch/MonoDevelop.Xml
