### ISSUE TITLE
Certain Literal Tokens are Shared

### ISSUE THREAD

**Issue by todor-dk** [KirillOsenkov/XmlParser#9]
Certain literal tokes are shared. This results that the token will change parent when another XML document is parsed. 
PROBLEM: It is no longer possible to ask for Parent / ParentElement and navigate the parse tree.

Example of cached token: Microsoft.Language.Xml.Scanner._xmlAmpToken.

Example in pseudocode: 
doc1 = Parser.ParseText(xml1);

// Important that something else that contains similar literals is parsed AFTER the result from the first parse is used.
doc2 = Parser.ParseText(xml2);

VisitChildren(doc1);

void VisitChildren(node)
{
    foreach(child in node.Children)
    {
        ASSERT(child.GetDocument() == node.GetDocument()); // <---- FAILS
        VisitChildren(child);
    }
}

**Comment by KirillOsenkov** [comment]
Yes, this is a known problem. But thanks for reporting a good test scenario.

**Comment by KirillOsenkov** [comment]
This https://github.com/KirillOsenkov/XmlParser/blob/master/src/Microsoft.Language.Xml/Syntax/SyntaxFactory.cs#L8 is shared mutated state :(

Discovered by https://github.com/KirillOsenkov/XmlParser/blob/master/src/Microsoft.Language.Xml.Tests/TestParser.cs#L147

Reported by @DavidKarlas

**Comment by garuma** [comment]
Hey,

With the switch to a proper green/red node separation there should be no more cases of shared nodes that are mutable and thus corrupting each other internal state. If I missed something feel free to re-open.
